# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: poojaagent

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    versionSpec: "11"
    jdkArchitectureOption: 'x64'
    javaHomeOption: 'JDKVersion'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      #!/bin/bash
      echo 'Hello world'
- task: CmdLine@2
  inputs:
    script: 'az group create --name poojagrp --location eastus'
             az vm create \
            --resource-group poojagrp \
            --name myVM \
            --image Debain \
            --public-ip-sku Standard \
            --admin-username azureuser
            --generate-ssh-keys
            